spring.application.name=ProductServiceOct7

logging.level.org.springframework.web.*=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productserviceoct7
spring.datasource.username=productserviceoct7user
#spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

server.port=${SERVER_PORT} //9000

user.service.baseUrl=http://localhost:8000/users
